version = 0.1
[default.deploy.parameters]
stack_name = "dream-companion"
resolve_s3 = true
s3_prefix = "dream-companion"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "JWTSecret=\"\""
image_repositories = []
confirm_changeset = true
