AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  Dream Companion App - A Flask-based application deployed using AWS SAM

Globals:
  Function:
    Timeout: 10
    Runtime: python3.11

Resources:
  DreamCompanionApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
        AllowCredentials: "'false'"
        MaxAge: "'300'"

  DreamCompanionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: wsgi.handler
      Runtime: python3.11
      CodeUri: src/
      Environment:
        Variables:
          FLASK_ENV: production
          S3_BUCKET_NAME: dream.storage
          PREMIUM_TABLE_NAME: dream-companion-premium-users
          MEMORIES_TABLE_NAME: dream-companion-memories
          FEEDBACK_TABLE_NAME: dream-companion-feedback
          STRIPE_SECRETS_ARN: arn:aws:secretsmanager:us-east-1:732408661603:secret:stripe-jm2Ua6-Kg9uMo
      Events:
        DreamCompanionApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref DreamCompanionApi
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - "s3:GetObject"
                - "s3:PutObject"
                - "s3:DeleteObject"
                - "s3:ListBucket"
              Resource: 
                - "arn:aws:s3:::dream.storage/*"
                - "arn:aws:s3:::dream.storage"
            - Effect: "Allow"
              Action:
                - "dynamodb:GetItem"
                - "dynamodb:PutItem"
                - "dynamodb:DeleteItem"
                - "dynamodb:UpdateItem"
                - "dynamodb:Query"
                - "dynamodb:Scan"
                - "dynamodb:CreateTable"
                - "dynamodb:DescribeTable"
              Resource: 
                - "arn:aws:dynamodb:*:*:table/dream-companion-premium-users"
                - "arn:aws:dynamodb:*:*:table/dream-companion-premium-users/*"
                - "arn:aws:dynamodb:*:*:table/dream-companion-memories"
                - "arn:aws:dynamodb:*:*:table/dream-companion-memories/*"
                - "arn:aws:dynamodb:*:*:table/dream-companion-feedback"
                - "arn:aws:dynamodb:*:*:table/dream-companion-feedback/*"
            - Effect: "Allow"
              Action:
                - "secretsmanager:GetSecretValue"
              Resource: 
                - "arn:aws:secretsmanager:us-east-1:732408661603:secret:stripe-jm2Ua6-Kg9uMo"

